name: Norminette

on:
  pull_request:
    paths:
      - '**.c'
      - '**.h'

jobs:
  norminette:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Install norminette
        run: python3 -m pip install norminette
        
      - name: Run norminette and save output
        id: norm
        run: |
          OUTPUT=$(norminette 2>&1) || true
          echo "NORM_OUTPUT<<EOF" >> $GITHUB_ENV
          echo "$OUTPUT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          
      - name: Comment PR
        uses: actions/github-script@v6
        with:
          script: |
            const output = process.env.NORM_OUTPUT;
            const hasFailed = output.includes('Error!');
            
            let comment = '## Norminette Check\n\n```\n' + output + '\n```\n\n';
            comment += hasFailed ? '❌ Norminette found style errors' : '✅ Norminette passed all checks';
            
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: comment
            });
