name: Norminette Check

on:
  push:
    branches:
      - main
      - github-actions-setup
    paths:
      - '**.c'
      - '**.h'
  pull_request:
    paths:
      - '**.c'
      - '**.h'

jobs:
  norminette:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Norminette
      run: |
        python -m pip install --upgrade pip
        python -m pip install norminette
        python -m pip list | grep norminette
        which norminette || true
        
    - name: Verify Norminette Installation
      run: |
        norminette --version
        
    - name: Run Norminette
      run: |
        for file in $(find . -type f \( -name "*.c" -o -name "*.h" \)); do
          echo "Checking $file..."
          norminette "$file" || exit 1
        done
